version: '3.1'

services:
  mongo:
    image: jvgc/prisma_mongo:latest
    restart: always
    env_file: .env
    ports:
      - 27017:27017
    networks:
      - mongo
  api:
    image: jvgc/tractian_node:latest
    volumes:
      - /usr/app/dist
      - /usr/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongo
networks:
  mongo: