version: '3.1'

services:
  mongo:
    build: ./mongodb
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: password
       MONGO_INITDB_DATABASE: db
       MONGO_REPLICA_HOST: mongo
       MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017
    networks:
      - mongo
  api:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/app
      - /usr/app/dist
      - /usr/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - mongo
    networks:
      - mongo
networks:
  mongo: