on:
  push:
    branches: [ci/gh-actions]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Build
        run: |
          yarn
          yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run lint
        run: |
          yarn
          yarn lint
